nome = input('Olá, qual o seu nome? ')
print ('Muito bem vindo, prazer em o conhecer sr/a,' , nome)
print ('Por favor digite a sua data de nascimento')
dia = input ('Dia =')
mes = input ('Mês =')
ano = input ('Ano =')
print (nome , ',você nasceu no dia' , dia , 'de' , mes , 'de' , ano ,'.')
correto = input ('Esta está informção correta?')
print ('Muito obrigado pela sua colaborção sr/a,' , nome , '.' 'Até uma proxima, boas programações')