n = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(n)))
print('É alfabético? {}'.format(n.isalpha()))
print('É um número? {}'.format(n.isnumeric()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('Está em minúsculas? {}'.format(n.islower()))
print('É imprimivél? {}'.format(n.isprintable()))
print('É um espaço? {}'.format(n.isspace()))
print('Está capitalizado? {}'.format(n.istitle()))
print('Está em maiúsculas? {}'.format(n.isupper()))